INSERT INTO users (name, serial_number, phone_number, address) VALUES
('Sukumar Sen', '125', '9426614428', 'B-204 Aditya greens, New C G Road, Chandkheda, Ahmedabad -382424'),
('Suman Das', '126', '9427629654', 'H-301, Parth Avenue, Near ONGC Avni Bhavan, Chandkheda, Ahmedabad, Pin 382424'),
('Suman Chakraborty', '127', '9428330177', '804, Setu Elegance, Behind D- Mart, Motera, Ahmedabad'),
('Swapan Kr Sadhukhan', '128', '9426613462', 'B 304, Sopan Appt, New CG Road, Chandkheda, A''bad'),
('Tanmoy Kumar Shit', '129', '9402141009', 'A/201 Sharan Residency New C.G Road, Chandkheda'),
('Tapan Ray', '130', '9979230582', 'D/5 Sopan Heights . New C.G Road . Ahmedabad -382424'),
('Tapas Nandi', '131', '9485138585', 'D-401, Aditya Antrix, TP-44, Chandkheda, A''bad'),
('Uttam Kumar Bhui', '132', '9426330369', 'B 901, Pebble Bay, Near Jantanagar BRTS, Chandkheda'),
('Uttam Mondal', '133', '9879162888', '304, Sharadam Estellla, Near Srinath Residency, Addai, Gandhinagar'),
('Vivek Talukdar', '134', '9428332961', '403, Saral Sky Suites, Near Sona crossing, New CG Road, Chandkheda, Ahmedabad 382424'),
('Biraj K Sheet', '135', '7665115673', 'B-406, Sopan Complex, near ICICI Bank, New CG Road, Chandkheda, Ahmedabad - 382424'),
('Dinesh Chandra Das', '136', '9638912993', 'B-504, Sakal Residency, Near Sakar School, New CG Road Chandkheda Ahmedabad - 382424'),
('Dr. Dhiman Basu', '137', '9925433861', 'A-801, Tanishk Enclave B/H Westside Shop (Sungrace Arcade) Chandkheda Ahmedabad -382424'),
('Dr. Tapan Kumar Paul', '138', '9426614591', 'A-303 Sopan Apt. New CG Road Chandkheda'),
('Palash/Priya Bose', '139', '8800097775', 'F-504, Sangath Platina, Motera, Ahmedabad'),
('Papia Mukherjee', '140', '9893921470', 'A-403 Setu Exotica New CG Road, Chandkheda'),
('Prantik Barma', '141', '7984324020', 'A 902 Pebble Bay Near Jantanagar BRTS New C. G. Road, Chandkheda, Ahmedabad: 382424'),
('S K Hazra Chaudhary', '142', '9428332344', 'B 103, Sakal Residency, New CG Road, Chandkheda'),
('Sudipta Chakraborty', '143', '9377475472', 'D 403 Pebble Bay, Near Janta Nagar, Chandkheda'),
('Sujit Kumar Biswas', '144', '9410390953', 'B-202, Sakal-24, Opposite Amrakunj Gracia Sakal Street, TP-44, Chandkheda, Ahmedabad'),
('Sulekha Neogi', '145', '9662119360', 'B-503, Setu Residency, Nr. Kena Bungalow, Motera'),
('Tapas Ghosh', '146', '9969222256', '103, Tower-5, Devnandan Heights, New CG Road, Chandkheda Ahmedabad 382424'),
('Tathagata Bose', '147', '6006138188', 'A/1103, K B Royal Serenity, Sarathi Bunglow Bus station, Chandkheda, Ahmedabad'),
('Shrestha Roy', '103', '9073383593', 'F-502, Ishan Silver, Near Sona Cross, New CG Road, Chandkheda Ahmedabad - 382424'),
('Shuvendu Roy', '104', '9998811122', 'B/97 Rajeshwari society, Near Chandkheda railway station, Chandkheda'),
('Shyama Prasad Hansda', '105', '9426612385', 'B-304, Ishan Luxuria, New C G Road, Chandkheda, Amd-382424'),
('Shyamal Bhattacharya', '106', '9727123223', '15/1, Maitri Avenue, Motera, Ahmedabad - 380005'),
('Shyamal Sen', '107', '9428008622', 'A 403 Maharaja Residency, New CG Road, Chandkheda, Ahmedabad'),
('Sibaprasad Ray', '108', '9428008529', '404 Devanandan Horizon, New C G Road, Chandkheda, Ahmedabad -382424'),
('Sirsendu Hati', '109', '9969222742', NULL),
('Soham Mahapatra', '110', '7384317325', 'B1-1104 Sangath Skyz Koteshwar, Bhat-Koteshwar Road Near ITER India office, Ahmedabad 380005'),
('Somnath Choudhury', '111', '7086058897', '19, Kalash Bunglaws Near ONGC Avani Bhavan Chandkheda, Ahmedabad-382424'),
('Somnath Karmakar', '112', '7574837490', 'C-604, Ishan Luxuria, New C G Road, Chandkheda'),
('Soumen Mukherjee', '113', '9898567919', 'A 602, Devanandan Alteza Off: New CG Road Chandkheda, Ahmedabad,382424'),
('Soumi Chatterjee', '114', '9586648367', 'A 502 K B Royal Phoenix. Nr Panchshlok Residency, New Chandkheda, Satyamev hospital Road, A''bad'),
('Soumik/Smritti Datta', '115', '9173057081', 'C-46, Sardakrupa Society, Opp Arena School, Jantanagar, Chandkheda Ahmedabad - 382424'),
('Soumitra Dev Sarkar', '116', '9426614348', 'D-503, Pebble Bay, Near Janta Nagar, Chandkheda'),
('Sourabh Dutta', '117', '7043341966', 'A-302, Devanandan Sky, Opposite Dhanvihar Residency, Chandkheda, 382424'),
('Sourav Mahato', '118', '9435718573', '304, Avani Dimora, Near Zundal Circle Chandkheda'),
('Subeer Majumdar', '119', '9818170750', 'DG, Gujarat Biotechnology University, GIFT City, Gandhinagar'),
('Subhash Barman', '120', '9664523877', 'A-504 Setu Exotica, opp. Devanandan Heights, New C.G Road Chandkheda ,Ahmedabad -382424'),
('Subir Bhadra', '121', '9435715550', 'A-303, Sarai Altezza, Near Srinath Bungalows-1, Chandkheda, Ahmedabad, Gujarat-382424'),
('Subir Debnath', '122', '9724043348', '1905, Subhash Nagar, Gujarat housing board, chandkheda.Ahmedabad.382424'),
('Subir Kumar Ghoshal', '123', '9879509504', 'T6/201, Devanandan Heights, Podar school lane, Chandkheda, Ahmedabad -382424'),
('Sujit Mitra', '124', '9426614760', 'D 903 Savvy Solaris, Motera , Ahmedabad 380005'),
('Partha Das', '84', '9428008714', 'K-402 Himalaya Zircon Motera Behind Sangath Mall-1 Ahmedabad-380005'),
('Prabhash Ghosh', '85', '9969224527', 'T6/701, Devnandan Heights, Chandkheda, Ahmedabad-382424'),
('Pradip Kumar Ghatuary', '86', '8980717858', 'E-203, E-Block Parshwanath Metro City, Opp . Astamangal Bungalows, TP-44 area, Chandkheda, Ahmedabad-382424'),
('Pradipta Biswas', '87', '9433301271', 'X 708 Eden Godrej Garden City Jagatpura Ahmedabad'),
('Pralay Nandi', '88', '9925039689', 'D/404 , Sangath Silver, Near 4D Square Mall, Motera ,Ahmedabad'),
('Pranay Pandit', '89', '9601012382', 'A-70, New Kamal Kunj Society, IOC Road, Chandkheda, Ahmedabad-382424'),
('Prasanta Kumar Sil', '90', '9428008305', '601, Tower No.: 3, Devnandan Heights, Opp. Avkar Bunglows, New C. G. Road, Chandkheda, Ahmedabad: 382424'),
('Prasanta Mondal', '91', '9428330282', 'E-803, Pebble Bay, BRTS New CG Road, Chandkheda, Ahmedabad. Pin- 382424.'),
('Rajib Bandyopadhyay', '92', '9909991602', '904, Saral Sky Suites, Sona Cross Road, New CG Road, Chandkheda, Ahmedabad 382424'),
('Rakesh Bhattacharya', '93', '9825374233', 'A-7/101, LA HABITAT Opp. Aayna Complex, Zydus Hospital Road, Thaltei, Ahmedabad - 380059'),
('Rakesh Sarkar', '94', '9402168377', 'D-404, Aditya Antrix, TP-44, Chandkheda, Ahmedabad - 382424'),
('Ranen Nath', '95', '8259949501', '17,Samruddhi Bunglows,New C G Road, Chandkheda, Abd-382424'),
('Ratan Kumar Basu', '96', '9824013970', '31 Amrakadamb Bungalows, Ramdeo Nagar, Satellite, Ahmedabad 380015'),
('Sabyasachi Pal', '97', '9428008846', 'A1001 Pebble Bay Near Janta Nagar Chandkheda'),
('Samir Mandal', '98', '9898382680', 'C/4,Nigam Nagar, Opp Jantanagar, New CG Road, Chandkheda, Ahmedabad'),
('Sandeep Ghosh', '99', '9426330315', 'A5, Kasturi Nagar, IFFCO Township, Kalol, Gandhinagar'),
('Santanu Kar', '100', '9427504787', 'B-501, East Ebony Apartment, Sona Cross Road, Chandkheda, Ahmedabad-382424.'),
('Santosh/Saswati Roy', '101', '8337034295', 'Keshav apartment, Block-3B, Room no -405, Chandkheda'),
('Sarojit Haldar', '102', '7574834205', '20, Jahanyi Bunglow-IV , Nr Sopan Heights, New C G Road, Chandkheda , Ahmedabad: 382424'),
('Ninak Mohan Ray', NULL, '9427504537', 'C-503, Shyam-84, Motera Stadium Road, Motera, Ahmedabad - 380005'),
('Indrajit Naskar', NULL, '9969227110', 'B-1001, East Ebony Apartment, Sona Cross Road, Chandkheda, Ahmedabad-382424.'),
('J K Mahapatra', NULL, '9428008579', 'D-101 Sharan Residency, New C.G.Road, Chandkheda, Ahmedabad-382424'),
('Jadab Mitra', NULL, '8153093571', 'C-3 Sopan Heights , Nr. Podar School , New C. G. Road, Chandkheda, Ahmedabad-382424'),
('Jaharial Datta', NULL, '9426614064', 'A601, Pebble Bay, Jantanagar, Chandkheda, Ahmedabad.'),
('Jayanta Kumar Ash', NULL, '9427504751', 'K B Royal Serenity, Near Ganthia Rath, Sabarmati Mehesana High Way Chandkheda, A''bad-382424'),
('Kalyan Kumar Kar', NULL, '9426612363', 'H 201, Sangath Platina, Motera, Ahmedabad'),
('Kankan Kumar Khara', NULL, '9428518712', '20 - Shrinath Bunglows - 2, Motera-Chandkheda Road, Chandkheda. Ahmedabad-382424'),
('Keshab Chandra Pal', NULL, '9512700749', '28 Swagat Bungalows-4 New CG Road Chandkheda, Ahmedabad - 382424'),
('Khushboo Saha Patel', NULL, '9930496998', 'D-804, Swagat Pelican, Thakar Farm Road Sargasan Gandhinagar'),
('Kingshuk Sarkar', NULL, '9818461494', '704, Sangath Diamond Tower, Motera, Ahmedabad - 380005'),
('Kuldip Mukherjee', NULL, '9969221990', 'A 504, East Ebony, Sona cross road, Chandkheda, Ahmedabad-382424'),
('M L (Shova) Dey', NULL, '9638650151', 'A/104, Shree Balaji Residency, Gandhinagar Highway, B/H D-Mart, Motera, Ahmedabad'),
('Mainak Bandyopadhyay', NULL, '9427050540', '47, Devshrusti-2 Bungalow, Motera, Sabarmati, Ahmedabad, 380 005'),
('Manotosh Kumar Basu', NULL, '8849349979', 'A401 Pebble Bay, Janta Nagar, Chandkheda, A''bad'),
('Milan Malakar', NULL, '9435717432', 'B-303 Shiti Ratna Avenue, Chandkheda Ahmedabad-382424'),
('Mriganka Roy', NULL, '7574840090', 'A/501, Pebble Bay, Nr. Jantanagar, Chandkheda, Ahmedabad-382424'),
('Narendra Kumar Dawn', NULL, '7405145019', 'E-304, Aditya Greens, Near Sahajanand City Bungalows, New CG Road, Chandkheda, A''bad'),
('Nihar Banerjee', NULL, '9428330002', 'B-73, West End Park, B/H. Gurudwara, S.G. Road, Thaltej'),
('Nilratan Chowdhury', NULL, '9427504020', 'A 502 Setu Residency, Opp Kena Bunglows, Motera Stadium Road, Motera, Ahmedabad.'),
('Nitish Roychowdhury', NULL, '9428330741', 'B-303, Sangath Silver, Nr. D-Mart-Gandhinagar HW, P.O Sabarmati, Ahmedabad-380005'),
('Debasis Basu', '43', '9426612333', 'B-203, Sukun Residency 1, New CG Road, Chandkheda, Ahmedabad -382424'),
('Debasis Sanyal', '44', '9490168000', 'A302 Sangath Pearl , Motera - 300005'),
('Debasish Mitra', '45', '9909020997', 'D/14 Park Avenue, Opp. Sona Sweet Home, New C G Road, Chandkheda, Ahmedabad, 382424'),
('Debjani Podder (R.N Poddar)', '46', '9924699011', 'A-302 Shree Balaji Residency, Motera Sabarmati Ahmedabad Gujarat 380005'),
('Devangshu Bhattacharya', '47', '9099006062', 'B-102, Shivansh Signature, near Madhuram Posh, TP-44, Chandkheda Ahmedabad - 382424'),
('Dibyendu Chatterjee', '48', '7016917464', 'AS01, Parmeshwar 8, New Chandkheda. Ahmedabad 382424'),
('Digvijoy Dev', '49', '7043784217', 'B/22 Sanskrit, Gandhinagar Highway, Sabarmati, Ahmedabad-380005'),
('Dilip Ranjan Ray', '50', '9426930160', '1/6, Swagat Residency, Motera, Near Motera Village, Ahmedabad -380005'),
('Dilip Subodh Dandapat', '51', '8780792740', 'A/88, swagat Bunglows -3, New CG Road, Chandkheda, Ahmedabad-382424'),
('Dr. Anand Kumar', '52', '9428057116', 'G-403, Ishan Silver, Near Sona Cross, New CG Road, Chandkheda Ahmedabad - 382424'),
('Dr. Joydeep Ghose', '53', '9427628353', 'D302 Samruddhi Residency, Opposite Krishna Bungalows-1, Motera, Ahmedabad, 380005'),
('Dr. Samir K Mahajan', '54', '8469921362', 'B903, Devnandan Altezza, New C G Road, Ahmedabad'),
('Dr. Subir Ghosh', '55', '9825581915', 'A-14, Sanskrit Bunglows, beside Tanisha Store, Visat Gandhinagar Highway'),
('Gauri Shankar Ghosh', '56', '9428330122', '52, Swagat Bungalows-4, New CG Road, Chandkheda, Ahmedabad-382424'),
('Gautam Das', '57', '9969228198', 'T6/602, Devnandan Heights, Off New CG Road, Chandkheda, Ahmedabad-382424'),
('Gobinda Singha', '58', '9428008856', '702, Sangath Diamond Tower, behind PVR cinema, 4Dsquare, Motera, Sabarmati, Ahmedabad-380005'),
('Gopal Das', '59', '9409194993', 'A-60, Aditya Bunglows Nr. Lambha Lake Indiranagar Road Lambha, Ahmedabad-382405'),
('Gopal Paul', '60', '9049883280', 'B-203, Sai Simran residency, TP-44, Near fire station, Chandkheda, Ahmedabad -382424'),
('Goutam Lahiri', '61', '9426612828', '25, Devpriya-3 Bungalow, Opp. Hari Om Society, Motera, Ahmedabad -380005'),
('Himangshu Kumar Roy', '62', '8000861718', 'C-504, Sopan(Opp ICICI Bank), New CG Road, Chandkheda, Ahmedabad'),
('Apurba Karmakar', NULL, '7043367155', '402, Shilp Synergy, Sona Cross Road, New CG Road, Chandkheda, Ahmedabad 382424'),
('Aritra Kundu', '22', '9968602007', 'F1103 Sharan Circle Homes Near Zundal Circle, Ahmedabad 382424'),
('Arnab Dasgupta', '23', '8306098020', 'D103, Dev pride, Motera, Ahmedabad'),
('Arun Prasad Purkait', '24', '9428518727', '12, Kamal Bungalows IOC Road, Chandkheda, Ahmedabad'),
('Asim Kumar Saha', '25', '9428330038', '12, Kamal Bungalows IOC Road, Chandkheda, Ahmedabad'),
('Asitava Majumder', '26', '9428008388', 'A-303, Sukun Residency 1 New C G Road, Chandkheda, Ahmedabad -382424'),
('BK (Sumona) Das', '27', '9898022895', '11 Devdarshan Bunglow, New CG Road, Chandkheda.'),
('BK Joardar', '28', '9664883617', '8 Suryanarayn bungalows-2 motera , Ahmedabad.'),
('Bablu Das', '29', '9316532613', 'B-8 Sanskrit Bungalows, Gandhinagar highway, Nr. Visat Petrol Pump, Motera, Ahmedabad-380005'),
('Banibrata Naskar', '30', '9435716620', 'Waterlily Adani shantigram Near Vaishnodevi Circle, S G Highway, Ahmedabad 382421'),
('Beauty Mazumdar', '31', '9898099261', '16/C, Devtirth Bungalow,Opp. Devkutir Bungalow, Sona Cross Road, New C.G.Road, Chandkheda, A''bad.'),
('Bhaswati/Manas Chakraborty', '32', '8320011498', 'Swagat Status 1, Opp Motera GGS, New CG Road, Chandkheda Ahmedabad'),
('Bikramjit Sanyal', '33', '9426612432', 'A-603, Devnandan Altezza, New C.G Road, Chandkheda, Ahmedabad -382424.'),
('Chanchal (Bela) Dass', '34', '9427950654', 'F 201 Parth Avenue, Near ONGC Avni Bhavan, Chandkheda, Ahmedabad, Pin 382424'),
('Chapal Kumar Das', '35', '9428008901', 'C-301, Maharaja Avenue, New CG Rd, Sona Cross Rd, Chandkheda, Ahmedabad, Gujarat, 382424'),
('Chinmoy Sarkar', '36', '9426612646', 'A-303,Shree Hari Blessing, New CG Road, Chandkheda, Ahmedabad PIN 382424'),
('Chittaranjan Bera', '37', '9426614581', 'T2/302, Devnandan Heights, Off New CG Road, Chandkheda, Ahmedabad'),
('Debaditya Sinha', '38', '9426614130', 'T6/103, Devnandan Heights New C.G. Road, Opp. Aavkar Bunglows, Chandkheda, A''bad-382424'),
('Debaprasad Das', '39', '9969220237', 'T-2/502, Devnandan Heights, Off New C G Road, Chandkheda, Ahmedabad -382424'),
('Debargha Mitra', '40', '9727702542', 'Sangath Pure, Nr DCIS Circle, 200 ft Ring Road, Chandkheda, Ahmedabad, Gujarat 382424'),
('Debashis Saraswati', '41', '9428008555', 'A-701 Devnandan Altezza, New CG Road, Chandkheda, Ahmedabad -382424'),
('Abhijit Chatterjee', '1', '9969225681', '32 Swagat Bunglows-1, New C G Road, Chandkheda Ahmedabad -382424'),
('Abhijit Chatterjee ISRO', '2', '9687611980', 'B-1004, Samvaad Samanvay, Tragad Underbridge, Near Lubi Corporate office, Ahmedabad 382470'),
('Abhijit Chaudhuri', '3', '8003897793', 'Tower-3, Flat-603, Devnandan Heights, New C G Road, Chandkheda, Ahmedabad - 382424'),
('Abhijit Chaudhury', '4', '7405464562', 'A-402, Sepal Elegant -3, Opp. Suryan Hope town, B/h. Satyamev Hospital. Chandkheda, A''bad-382424'),
('Ajit Kumar Pal', '5', '9490168701', 'Flat No.503, Sangath Diamond Tower, TP-21, Opp. Savvy Solaris, Motera, Ahmedabad-380005'),
('Ajoy Kumar Das', '6', '9426614468', 'F-601, Sangath Posh, Nr DCIS Circle, 200 ft Ring Road, Chandkheda, Ahmedabad, Gujarat, 382424'),
('Aloke (Tapashi) Ray', '7', '9825323291', 'E 104, Parshwanath Metrocity, Chandkheda, Ahmedabad -382424'),
('Aloke Bhowal', '8', '8132978064', 'C-15, Western Sector, ONGC Colony, Ahmedabad'),
('Aloke Roychowdhury', '9', '9824688327', 'B - 703 Satyamev Royal 3, Near Dutt Avalon, Mansarovar Road, Chandkheda, Ahmedabad - 382424'),
('Aloknath Biswas', '10', '9426614924', 'C-403 Sakal Residency, New CG Road, Chandkheda, Ahmedabad'),
('Amit Mukhopadhyay', '11', '9428330807', '20, Sahajanand Villa-2, New C G Road, Chandkheda, Ahmedabad -382424'),
('Ananda Kumar Biswas', '12', '9428008965', 'B-5 deep bhoomi residency-1; Nr. ONGC Colony; Chandkheda;Ahmedabad; Gujarat; 382424'),
('Ananda kumar Ray', '13', '9868393325', '89,Shrinath Residency-2, Adalaj, Gandhinagar, Gujarat, 382421'),
('Anil Chandra Laskar', '14', '9408498761', 'A-202,Sukan Residency, New C.G Road, Chandkheda'),
('Aninda Ghosh', '15', '9410390125', 'C-503, Aditya Greens, Nigam Nagar, Chandkheda, Ahmedabad'),
('Anindya (Lovely) Ghosh', '16', '9426612378', 'C-1004, Sarthak Tower, Ramdevnagar, Satellite, Ahmedabad, 380015'),
('Anirban Basak', '17', '9985963173', 'A-402, Sukun Residency, New CG road, Chandkheda'),
('Anjan Kumar Deb', '18', '9428008695', '902,Devnandan Horizon Off New CG Road, Chandkheda'),
('Anup/Basabi Mondal', '19', '9426614046', 'F-502, Sangath Posh, Near DCIS circle, Chandkheda'),
('Anupa Naskar', '20', '9898590716', 'A-301 Sukun Residency -1, B/h. Sakar school New CG Road, Chandkheda, Ahmedabad 382424'),
('Anurup Das', '21', '9427504247', 'D-202 Shukan Orchid, New CG Road, Chandkheda');





-- Insert unique authors into the authors table
INSERT INTO authors (name, details) VALUES
('SANTOSH KUMAR GHOSH', 'Bengali writer known for realistic narratives and social themes'),
('SYED MUSTAFA SIRAJ', 'Creator of Colonel Niladri Sarkar, known for psychological depth'),
('NIRPENDRA SANYAL', 'Bengali translator and writer'),
('SHUBHASH CHANDRA CHATTOPADHDHYAY', 'Author of agricultural and health-related works'),
('SUBIMAL CHANDRA DEY', 'Bengali writer focusing on practical guides'),
('NIRMAL KUMAR ROY', 'Author of spiritual and devotional literature'),
('ASHISH TARU MUKHOPADHYAY', 'Biographer and Bengali writer'),
('SHANKU MAHARAJ', 'Travel and fiction writer'),
('ARUP RATAN BHATACHARAY', 'Author of educational and quiz books'),
('AMARNATH ROY', 'Bengali writer of intellectual works'),
('PARTTOSH MAJUMDER', 'Adventure and historical fiction writer'),
('DEVI PRASAD BONDOPADHYAY', 'Author of hunting and adventure stories'),
('PARESH CHANDRA MAJUMDER', 'Agricultural writer'),
('SHANKAR', 'Renowned for novels like Chowringhee, blending humor and social commentary'),
('SUNIL GANGOPADHYAY', 'Prolific novelist and poet, known for historical novels'),
('VIKKAMADITYA', 'Pseudonym for a Bengali writer of historical narratives'),
('AMALENDU CHARABORTI', 'Bengali novelist'),
('NARENDRA DEY', 'Poet and translator of classical works'),
('DR SUBRATA SEN', 'Medical and health writer'),
('RAMA PADA CHOUDHARY', 'Bengali novelist known for social themes'),
('SHIRSHENDU MUKHOPADHADHYAY', 'Versatile author of novels and children’s literature'),
('DR VISHNU BASU', 'Compiler of world classics'),
('AVRA ROY', 'Bengali poet and writer'),
('MATI NANDI', 'Sports and fiction writer'),
('BIMAL KAR', 'Author of psychological and social novels'),
('SUCHITRA BHATTACHARYA', 'Popular novelist focusing on human relationships'),
('BANAPHUL', 'Renowned for short stories and novels'),
('SAMARESH MAJUMDER', 'Author of socio-political novels like Kaalbela'),
('BUDDHA DEV GUHA', 'Known for nature-centric and romantic novels'),
('PRAFULLA ROY', 'Author depicting rural life, Sahitya Akademi Award winner'),
('SANUB CHATTOPADHYAY', 'Bengali humorist and novelist'),
('BIMAL MITRA', 'Author of epic novels like Saheb Bibi Golam'),
('SYED MUJTABA ALI', 'Travel writer and humorist'),
('KAMAL KUMAR MAUIMDAR', 'Bengali novelist'),
('BUDDHA DEV BASU', 'Modernist Bengali writer'),
('PREMENDRA MITRA', 'Poet and novelist, known for Ghanada series'),
('ASHUTOSH MUKHOPADHYAY', 'Bengali novelist and short story writer'),
('ASHAPURNA DEVI', 'Renowned for women-centric novels'),
('NIRSINHA PRASAD BHADURI', 'Bengali writer of mythological narratives'),
('SHIBRAM CHAKRABORTY', 'Humorist and children’s writer'),
('NARAYAN SANYAL', 'Author of detective and historical novels'),
('NIMA BHATTACHARYA', 'Bengali novelist'),
('TASLIMA NASRIN', 'Controversial author and activist'),
('KINNAR ROY', 'Bengali poet and novelist'),
('JAY GOSWAMI', 'Modern Bengali poet'),
('JHARESWAR CHOTTOPANYAY', 'Bengali writer'),
('HARSHA DUTTA', 'Bengali novelist'),
('AVANINDRA NATH THAKUR', 'Bengali writer'),
('ANITA AGNHOTRI', 'Author of socially relevant novels'),
('DEV SAHITYA KUTHIR', 'Publishing house, not an individual author'),
('TILOTTAMA MAJUMDER', 'Contemporary Bengali novelist'),
('GRANTHA NILOV', 'Publisher of translated world classics'),
('SRI ARAVINDA', 'Spiritual leader and writer'),
('SRIMA', 'Spiritual writer and disciple of Sri Aurobindo'),
('PRAHLAD KUMAR SEN', 'Spiritual and philosophical writer'),
('NIROD BARAN', 'Biographer of spiritual figures'),
('SJUDIFTA SENGUPTA', 'Bengali travel writer'),
('MANUARI DAS', 'Bengali travelogue writer'),
('SUTAPA SENGUPTA', 'Historian and writer'),
('SAMAT GANGOPADHYAY', 'Typo for Sunil Gangopadhyay or a related writer'),
('MATREVI DEVI', 'Bengali writer'),
('MANI RATNA MUKHOPADHYAY', 'Bengali novelist'),
('BISWA DEV BISWAS', 'Travel and adventure writer'),
('GAUR KISHOR GHOSH', 'Journalist and novelist'),
('ASHOK SENGUPTA', 'Travel writer'),
('KALYAN CHAUDHARI', 'Bengali historian'),
('AMARENDRA CHAKRABORTI', 'Travel and fiction writer'),
('IMBANITA DEBSEN', 'Bengali writer'),
('BIMAL MUKHEDEE', 'Typo for Bimal Mukherjee, travel writer'),
('UTPAL BANDOPADHYAY', 'Travel writer'),
('ATUL CHANDRA GUPTA', 'Bengali writer'),
('AMLAN DUTTA', 'Economist and essayist'),
('GOUTAM BHADRA', 'Historian'),
('JAWHARIAL NEHRU', 'Indian statesman and writer'),
('DHIRESH CHANDRA BHATTACHARYA', 'Historian and mythological writer'),
('MUHAMMAD UNUS', 'Economist, known for Grameen Bank'),
('AMARTYA SEN', 'Nobel laureate economist and writer'),
('AJIT KUMAR BASU', 'Bengali historian'),
('T.N. SESHAN', 'Indian administrator and writer'),
('A.P.I.ABDUL KALAM AZAD', 'Typo for A.P.J. Abdul Kalam, scientist and president'),
('NIMAI SADHAN BASU', 'Biographer of Vivekananda'),
('RUKMA DAKSHI', 'Bengali food and culture writer'),
('ASHOK RUDRA', 'Economist and writer'),
('M.I.AKGAR', 'Bengali writer, limited info'),
('SUKHMAY BHATTACHARYA', 'Mythological writer'),
('SVARI BREMLI', 'Biographer, likely a translator'),
('ANJAN MITRA', 'Cultural historian'),
('TAPAN ROY CHOUDHARY', 'Historian and writer'),
('SWAMI LOKESHARANANDA', 'Spiritual writer'),
('SHIPRA SARKAR', 'Bengali writer and historian'),
('ANAMITRA DAS', 'Co-author with Shipra Sarkar'),
('BMWG CAMERON', 'Unclear, likely a typo or collective author'),
('MARISHA KILANHELTER', 'Unclear, likely a typo or foreign author'),
('JOHTYK AKHORELKE', 'Unclear, likely a typo'),
('SURESH CHANDRA BANDYOPADHYAY', 'Mythological and legal writer'),
('J.D.BARNAL', 'Scientist and historian, likely J.D. Bernal'),
('LOKESHAWAR BASU', 'Bengali historian'),
('BRATINDRA NATII MUKHOPADHYAY', 'Art historian'),
('MINIDRA BIUSHAN GUPTA', 'Art historian'),
('NANDA DULAL DEY', 'Bengali diarist'),
('RAMABIR CHAKRABORTY', 'Historian'),
('BHABANI PRASAD CHAKRABORTY', 'Historian'),
('JAYANTANUI BANDOPADHYAY', 'Philosopher and writer'),
('SHARMILA BASU', 'Bengali biographer'),
('JAGMOHON MUKHOPADHYAY', 'Essayist'),
('ANANDA PUBLISHERS', 'Publishing house, not an author'),
('BANI BASU', 'Contemporary novelist'),
('AMITA AGNIHOTRI', 'Typo for Anita Agnihotri'),
('TARUN KUMAR BHAOURI', 'Bengali writer, limited info'),
('SUKANTA GANGOPADHYAY', 'Poet, related to Sunil Gangopadhyay'),
('MANNA DEY', 'Playback singer and autobiographer'),
('SUKANTA CHATTAPADHYAY', 'Poet, likely Sukanta Bhattacharya'),
('DHRITIKANTA LAHIRI CHOUDHURI', 'Bengali writer'),
('KALKUT', 'Pseudonym for Samaresh Basu'),
('LILA MAUIMDER', 'Typo for Leela Majumdar, children’s writer'),
('SMARAANJIT CHAKRABORTY', 'Contemporary novelist'),
('KETAKI KUSHARI DYSAN', 'Bengali novelist and essayist'),
('JASHAVANT SINGHA', 'Historian, likely Jaswant Singh'),
('AMITAVA GHOSH', 'Typo for Amitav Ghosh, novelist'),
('SATYAJIT ROY', 'Filmmaker and writer'),
('SUSHIL CHOUDHARY', 'Bengali historian'),
('SUDHIR CHAKRABORTY', 'Folk culture writer'),
('PACHYAJAN', 'Unclear, likely a typo or collective'),
('SUBHASH CHANDRA BOSE', 'Freedom fighter and writer'),
('AASHUTOSH MITRA', 'Bengali writer'),
('NAVA KUMAR BASU', 'Bengali short story writer'),
('NILKANTHA GHOSHAL', 'Bengali novelist'),
('SOLEMANJA BOOK HOUSE', 'Publisher, not an author'),
('SUSHANTA KUMAR SAHITYARATNA', 'Bengali biographer'),
('TARAPADA RAHA', 'Bengali short story writer'),
('SHRIM KATHITA', 'Compiler of Ramakrishna’s teachings'),
('USTAD BILAYET KHAN', 'Musician and autobiographer'),
('UPENDRA KISHORE ROY CHOUDHARY', 'Children’s writer and publisher'),
('RANJIT CHATTOPADHYAY', 'Compiler of ghost stories'),
('NEERAD CHANDRA CHOUDHARY', 'Literary critic');

-- Insert books into the books table
INSERT INTO books (serial_number, title, author_id, location) VALUES
('B/0117', 'SANTOSH KUMAR GHOSH', (SELECT id FROM authors WHERE name='SANTOSH KUMAR GHOSH'), 'Library Shelf'),
('B/0118', 'ALIK MANUSH', (SELECT id FROM authors WHERE name='SYED MUSTAFA SIRAJ'), 'Library Shelf'),
('B/0119', 'BICHAR (Frant Kafta : Translation)', (SELECT id FROM authors WHERE name='NIRPENDRA SANYAL'), 'Library Shelf'),
('B/0121', 'PRAKRITIK UPAJAME ROGAROYA O NIVANTRAN', (SELECT id FROM authors WHERE name='SHUBHASH CHANDRA CHATTOPADHDHYAY'), 'Library Shelf'),
('B/0122', 'TABE PHUL, PHAL O SABJI', (SELECT id FROM authors WHERE name='SUBIMAL CHANDRA DEY'), 'Library Shelf'),
('B/0123', 'SRI SRI RAMKRISHNA SANSPARSHE', (SELECT id FROM authors WHERE name='NIRMAL KUMAR ROY'), 'Library Shelf'),
('B/0124', 'MAHA NAYIKA SUCHITRA', (SELECT id FROM authors WHERE name='ASHISH TARU MUKHOPADHYAY'), 'Library Shelf'),
('B/0125', 'URVASHI ETENSE', (SELECT id FROM authors WHERE name='SHANKU MAHARAJ'), 'Library Shelf'),
('B/0126', 'BELGIUM THEKE BABHERIA', (SELECT id FROM authors WHERE name='SHANKU MAHARAJ'), 'Library Shelf'),
('B/0127', 'MATHEMATICS QUIZ', (SELECT id FROM authors WHERE name='ARUP RATAN BHATACHARAY'), 'Library Shelf'),
('B/0128', 'BUDDHI BICHAR', (SELECT id FROM authors WHERE name='ARUP RATAN BHATACHARAY'), 'Library Shelf'),
('B/0129', 'BUDDHIR KIELA', (SELECT id FROM authors WHERE name='AMARNATH ROY'), 'Library Shelf'),
('B/0130', 'AFRIKAR BANE JANGALE', (SELECT id FROM authors WHERE name='PARTTOSH MAJUMDER'), 'Library Shelf'),
('B/0131', 'SHIKARER BICHITRA KAHINI', (SELECT id FROM authors WHERE name='DEVI PRASAD BONDOPADHYAY'), 'Library Shelf'),
('B/0132', 'BANCIA BANAN BIDHI', (SELECT id FROM authors WHERE name='PARESH CHANDRA MAJUMDER'), 'Library Shelf'),
('B/0133', 'ORRISHAR NIRVACHITA GALPO', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0134', 'NIRBACHITA HINDI GALPO', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0135', 'SWADIHNATAR AJANA KATHA', (SELECT id FROM authors WHERE name='VIKKAMADITYA'), 'Library Shelf'),
('B/0136', 'HITLARER DIARY', (SELECT id FROM authors WHERE name='PARTTOSH MAJUMDER'), 'Library Shelf'),
('B/0137', 'MIRE CAMP', (SELECT id FROM authors WHERE name='PARTTOSH MAJUMDER'), 'Library Shelf'),
('B/0138', 'JABAJUVAN', (SELECT id FROM authors WHERE name='AMALENDU CHARABORTI'), 'Library Shelf'),
('B/0139', 'MEGH DUTT', (SELECT id FROM authors WHERE name='NARENDRA DEY'), 'Library Shelf'),
('B/0140', 'ROBAVAT O OMARKHAYYAM', (SELECT id FROM authors WHERE name='NARENDRA DEY'), 'Library Shelf'),
('B/0141', 'GACH PALATEO ASHUKH SAÑE', (SELECT id FROM authors WHERE name='SHUBHASH CHANDRA CHATTOPADHDHYAY'), 'Library Shelf'),
('B/0142', 'HAZAM O PETER ROG', (SELECT id FROM authors WHERE name='DR SUBRATA SEN'), 'Library Shelf'),
('B/0143', 'KHARIJ', (SELECT id FROM authors WHERE name='RAMA PADA CHOUDHARY'), 'Library Shelf'),
('B/0144', 'JAO PAKHI', (SELECT id FROM authors WHERE name='SHIRSHENDU MUKHOPADHADHYAY'), 'Library Shelf'),
('B/0145', 'GHUN POKA', (SELECT id FROM authors WHERE name='SHIRSHENDU MUKHOPADHADHYAY'), 'Library Shelf'),
('B/0146', 'PARA PAR', (SELECT id FROM authors WHERE name='SHIRSHENDU MUKHOPADHADHYAY'), 'Library Shelf'),
('B/0147', 'ISHVAR PRITHIBI BHALOBASA', (SELECT id FROM authors WHERE name='SHIRSHENDU MUKHOPADHADHYAY'), 'Library Shelf'),
('B/0148', 'WORLD CLASSICS', (SELECT id FROM authors WHERE name='DR VISHNU BASU'), 'Library Shelf'),
('B/0149', 'HRIDAITER SHABDO', (SELECT id FROM authors WHERE name='AVRA ROY'), 'Library Shelf'),
('B/0150', 'ACHEMA AJANA VIVEKANANDA', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0151', 'SHIBI', (SELECT id FROM authors WHERE name='MATI NANDI'), 'Library Shelf'),
('B/0152', 'TARA TIN JAN', (SELECT id FROM authors WHERE name='BIMAL KAR'), 'Library Shelf'),
('B/0153', 'DEKHI MAI PHIRE', (SELECT id FROM authors WHERE name='SAMARESH BASU'), 'Library Shelf'),
('B/0154', 'KACHHER MANUSH', (SELECT id FROM authors WHERE name='SUCHITRA BHATTACHARYA'), 'Library Shelf'),
('B/0155', 'DASTI UPANYAS', (SELECT id FROM authors WHERE name='SUCHITRA BHATTACHARYA'), 'Library Shelf'),
('B/0156', 'SUKH DUKH', (SELECT id FROM authors WHERE name='SUCHITRA BHATTACHARYA'), 'Library Shelf'),
('B/0157', 'SAHELI', (SELECT id FROM authors WHERE name='SUCHITRA BHATTACHARYA'), 'Library Shelf'),
('B/0158', 'DURBIN', (SELECT id FROM authors WHERE name='SHIRSHENDU MUKHOPADHADHYAY'), 'Library Shelf'),
('B/0159', 'PURBA PASCHIM PART 1', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0160', 'PURBA PASCHIM PART 2', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0161', 'BAMA PHULER CHOTO GOLPO SAMAGRA (PART-1)', (SELECT id FROM authors WHERE name='BANAPHUL'), 'Library Shelf'),
('B/0162', 'BAMA PHULER CHOTO GOLPO SAMAGRA (PART-2)', (SELECT id FROM authors WHERE name='BANAPHUL'), 'Library Shelf'),
('B/0163', 'PANCHTI PREMER KAHINI', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0164', 'SAT KAHAN PART 1', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0165', 'SAT KAHAN PART 2', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0166', 'MEYERA JEMAN HOI', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0167', 'KAL BELA', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0168', 'SINGHA VAHINI PART 2', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0169', 'BHALO THEKO, BHALOBASO', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0170', 'UTTARAOHIKAR', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0171', 'DASTI UPPANYAS', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0172', 'KOZAGAR', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0173', 'PREMER GOLPO', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0174', 'RIVU (PART-1)', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0175', 'RIVU (PART-2)', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0176', 'PARAKIA PREM', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0177', 'BAMA YOSTSNAI SABUI ANDHAKARE (PART-1)', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0178', 'BAMA YOSTSNAI SABUI ANDHAKARE (PART-2)', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0179', 'ANYA CHOKHE', (SELECT id FROM authors WHERE name='BUDDHA DEV GUHA'), 'Library Shelf'),
('B/0180', 'KEYA PATAR NAUKO', (SELECT id FROM authors WHERE name='PRAFULLA ROY'), 'Library Shelf'),
('B/0181', 'AKASHER NICHE MANUSH', (SELECT id FROM authors WHERE name='PRAFULLA ROY'), 'Library Shelf'),
('B/0182', 'PURBA PARVATI', (SELECT id FROM authors WHERE name='PRAFULLA ROY'), 'Library Shelf'),
('B/0183', 'KRANTI KAAL', (SELECT id FROM authors WHERE name='PRAFULLA ROY'), 'Library Shelf'),
('B/0184', 'NIRBACHITA RAMMYA RACHANA SAMAGRA', (SELECT id FROM authors WHERE name='SANUB CHATTOPADHYAY'), 'Library Shelf'),
('B/0185', 'SHRICHARAN KAMALE', (SELECT id FROM authors WHERE name='SANUB CHATTOPADHYAY'), 'Library Shelf'),
('B/0186', 'KEMON ACHHO BHAI', (SELECT id FROM authors WHERE name='SANUB CHATTOPADHYAY'), 'Library Shelf'),
('B/0187', 'PEYALA PIRICH', (SELECT id FROM authors WHERE name='SANUB CHATTOPADHYAY'), 'Library Shelf'),
('B/0188', 'SOFA CUM BED', (SELECT id FROM authors WHERE name='SANUB CHATTOPADHYAY'), 'Library Shelf'),
('B/0189', 'UIAN BEYE JAI', (SELECT id FROM authors WHERE name='SANUB CHATTOPADHYAY'), 'Library Shelf'),
('B/0190', 'ASHAMI HAZIR', (SELECT id FROM authors WHERE name='BIMAL MITRA'), 'Library Shelf'),
('B/0191', 'PARASTRI', (SELECT id FROM authors WHERE name='BIMAL MITRA'), 'Library Shelf'),
('B/0192', 'CHOURANGI', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0193', 'MANAB SAGAR TIRE', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0194', 'KATO AJANARE', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0195', 'EK DIN HATATH', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0196', 'RACHANA SAMAGRA', (SELECT id FROM authors WHERE name='ADYATA MALLO BARDHAN'), 'Library Shelf'),
('B/0197', 'TISTA PARER BRITTANTA', (SELECT id FROM authors WHERE name='DEBESH ROY'), 'Library Shelf'),
('B/0198', 'DESER MATI', (SELECT id FROM authors WHERE name='SHANKU MAHARAJ'), 'Library Shelf'),
('B/0199', 'SWAPNA DEKHAR ADHIKAR', (SELECT id FROM authors WHERE name='MAHASWETA DEVI'), 'Library Shelf'),
('B/0200', 'LOUHA KAPAT', (SELECT id FROM authors WHERE name='JARASANDHA'), 'Library Shelf'),
('B/0201', 'BABU BRITTANTA O PRASANGIC', (SELECT id FROM authors WHERE name='SAMAR SEN'), 'Library Shelf'),
('B/0202', 'KATHA SAHITYA JIGYASHA', (SELECT id FROM authors WHERE name='ALOK ROY'), 'Library Shelf'),
('B/0203', 'DESHE VIDESHE', (SELECT id FROM authors WHERE name='SYED MUJTABA ALI'), 'Library Shelf'),
('B/0204', 'CHACHA KAHINI', (SELECT id FROM authors WHERE name='SYED MUJTABA ALI'), 'Library Shelf'),
('B/0205', 'ANTARIALLIATEA', (SELECT id FROM authors WHERE name='KAMAL KUMAR MAUIMDAR'), 'Library Shelf'),
('B/0206', 'SHRESTIO GOLPO', (SELECT id FROM authors WHERE name='BUDDHA DEV BASU'), 'Library Shelf'),
('B/0207', 'SHRESTHA GALPO', (SELECT id FROM authors WHERE name='PREMENDRA MITRA'), 'Library Shelf'),
('B/0208', 'PARA KAPALE RAJA RANI (PART-1)', (SELECT id FROM authors WHERE name='ASHUTOSH MUKHOPADHYAY'), 'Library Shelf'),
('B/0209', 'PARA KAPALE RAJA RANI (PART-2)', (SELECT id FROM authors WHERE name='ASHUTOSH MUKHOPADHYAY'), 'Library Shelf'),
('B/0210', 'EKTI BISWASER JANMA', (SELECT id FROM authors WHERE name='ASHUTOSH MUKHOPADHYAY'), 'Library Shelf'),
('B/0211', 'JAKHAN DHAL NAM-E', (SELECT id FROM authors WHERE name='ASHUTOSH MUKHOPADHYAY'), 'Library Shelf'),
('B/0212', 'BISWAS ABISWAS', (SELECT id FROM authors WHERE name='ASHAPURNA DEVI'), 'Library Shelf'),
('B/0213', 'UPAKHYAN MALA', (SELECT id FROM authors WHERE name='BIMAL KAR'), 'Library Shelf'),
('B/0214', 'SUK SAPTATI', (SELECT id FROM authors WHERE name='NIRSINHA PRASAD BHADURI'), 'Library Shelf'),
('B/0215', 'EK MEYE BYOMKESHER KAHINI', (SELECT id FROM authors WHERE name='SHIBRAM CHAKRABORTY'), 'Library Shelf'),
('B/0216', 'MROTYOMA AMRITYOM', (SELECT id FROM authors WHERE name='NARAYAN SANYAL'), 'Library Shelf'),
('B/0217', 'MEM SAHEB', (SELECT id FROM authors WHERE name='NIMA BHATTACHARYA'), 'Library Shelf'),
('B/0218', 'BISWAS GHATAK', (SELECT id FROM authors WHERE name='NARAYAN SANYAL'), 'Library Shelf'),
('B/0219', 'SUITANUKA EKTI DEVDASIR NAM', (SELECT id FROM authors WHERE name='NARAYAN SANYAL'), 'Library Shelf'),
('B/0220', 'A.D.C', (SELECT id FROM authors WHERE name='NIMA BHATTACHARYA'), 'Library Shelf'),
('B/0221', 'FARASHI PREMIK', (SELECT id FROM authors WHERE name='TASLIMA NASRIN'), 'Library Shelf'),
('B/0222', 'SEI SAB ANDHOKAR', (SELECT id FROM authors WHERE name='TASLIMA NASRIN'), 'Library Shelf'),
('B/0223', 'AMAR MEYE BELA', (SELECT id FROM authors WHERE name='TASLIMA NASRIN'), 'Library Shelf'),
('B/0224', 'MEGH PATAL', (SELECT id FROM authors WHERE name='KINNAR ROY'), 'Library Shelf'),
('B/0225', 'ROUDRA CHHAYAR SANKALAN', (SELECT id FROM authors WHERE name='JAY GOSWAMI'), 'Library Shelf'),
('B/0226', 'STRIKER', (SELECT id FROM authors WHERE name='MATI NANDI'), 'Library Shelf'),
('B/0227', 'PUBER MEGH DAKSHINER AKASH', (SELECT id FROM authors WHERE name='JHARESWAR CHOTTOPANYAY'), 'Library Shelf'),
('B/0228', 'PRAKITI PATH', (SELECT id FROM authors WHERE name='KINNAR ROY'), 'Library Shelf'),
('B/0229', 'ARANYER DIN RATRI', (SELECT id FROM authors WHERE name='SJUNI GANGOPADHYAY'), 'Library Shelf'),
('B/0230', 'MAYURAKSHI TUME DILE', (SELECT id FROM authors WHERE name='HARSHA DUTTA'), 'Library Shelf'),
('B/0231', 'KAU DASHER MEGH DUT', (SELECT id FROM authors WHERE name='BUDDHA DEV BASU'), 'Library Shelf'),
('B/0232', 'APAN PAR', (SELECT id FROM authors WHERE name='AVANINDRA NATH THAKUR'), 'Library Shelf'),
('B/0233', 'KOLKATAR PRATIMA SHIPIRA', (SELECT id FROM authors WHERE name='ANITA AGNHOTRI'), 'Library Shelf'),
('B/0234', 'CHOTODER BOOK OF KNOWLEDGE', (SELECT id FROM authors WHERE name='DEV SAHITYA KUTHIR'), 'Library Shelf'),
('B/0235', 'CHANDER GAYE CHAND', (SELECT id FROM authors WHERE name='TILOTTAMA MAJUMDER'), 'Library Shelf'),
('B/0236', 'DWIKHANDITA', (SELECT id FROM authors WHERE name='TASLIMA NASRIN'), 'Library Shelf'),
('B/0237', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 17', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0238', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 18', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0239', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 19', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0240', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 20', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0241', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 21', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0242', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 22', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0243', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 23', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0244', 'VISHWER SHESTHA UPANYAS O CHOTA GOLPO 24', (SELECT id FROM authors WHERE name='GRANTHA NILOV'), 'Library Shelf'),
('B/0245', 'JYOG SADHANER BHITTI', (SELECT id FROM authors WHERE name='SRI ARAVINDA'), 'Library Shelf'),
('B/0246', 'DHYAN O EKAGRATA', (SELECT id FROM authors WHERE name='SRIMA'), 'Library Shelf'),
('B/0247', 'SRI ARABINDER BANGLA RACHANA', (SELECT id FROM authors WHERE name='SRI ARAVINDA'), 'Library Shelf'),
('B/0248', 'SIKSHA', (SELECT id FROM authors WHERE name='SRIMA'), 'Library Shelf'),
('B/0249', 'JIBON O JOG', (SELECT id FROM authors WHERE name='PRAHLAD KUMAR SEN'), 'Library Shelf'),
('B/0250', 'SRIMAYER JEEVAN KATHA', (SELECT id FROM authors WHERE name='NIROD BARAN'), 'Library Shelf'),
('B/0251', 'ANTARTIKA', (SELECT id FROM authors WHERE name='SJUDIFTA SENGUPTA'), 'Library Shelf'),
('B/0252', 'MISHAR DEHKE ELAM', (SELECT id FROM authors WHERE name='MANUARI DAS'), 'Library Shelf'),
('B/0253', 'CHHABIR DESHE KAVITAR DESHE', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0254', 'GREECE O ITALIR PRACHIN BIHUMITE', (SELECT id FROM authors WHERE name='SUTAPA SENGUPTA'), 'Library Shelf'),
('B/0255', 'AMERICAR DIARY', (SELECT id FROM authors WHERE name='SAMAT GANGOPADHYAY'), 'Library Shelf'),
('B/0256', 'ACHEMA CHIN', (SELECT id FROM authors WHERE name='MATREVI DEVI'), 'Library Shelf'),
('B/0257', 'MINI KIVAN', (SELECT id FROM authors WHERE name='MANI RATNA MUKHOPADHYAY'), 'Library Shelf'),
('B/0258', 'PAHAR THEKE PAHARE', (SELECT id FROM authors WHERE name='BISWA DEV BISWAS'), 'Library Shelf'),
('B/0259', 'NANADAKANTA NANDA GHUNTI', (SELECT id FROM authors WHERE name='GAUR KISHOR GHOSH'), 'Library Shelf'),
('B/0260', 'CHEMA ACHEMAR CHIN', (SELECT id FROM authors WHERE name='ASHOK SENGUPTA'), 'Library Shelf'),
('B/0261', 'MAHA CHINER PRATHIK', (SELECT id FROM authors WHERE name='KALYAN CHAUDHARI'), 'Library Shelf'),
('B/0262', 'SERA BHRAMAN KAHINI (PART-1)', (SELECT id FROM authors WHERE name='AMARENDRA CHAKRABORTI'), 'Library Shelf'),
('B/0263', 'SERA BHRAMAN KAHINI (PART-2)', (SELECT id FROM authors WHERE name='AMARENDRA CHAKRABORTI'), 'Library Shelf'),
('B/0264', 'BANDHU BHARA VASUNDRA', (SELECT id FROM authors WHERE name='AMARENDRA CHAKRABORTI'), 'Library Shelf'),
('B/0265', 'BHARAMANER NAVANITA', (SELECT id FROM authors WHERE name='IMBANITA DEBSEN'), 'Library Shelf'),
('B/0266', 'DU CHAKAY DUNIA', (SELECT id FROM authors WHERE name='BIMAL MUKHEDEE'), 'Library Shelf'),
('B/0267', 'DESHE DESHE DISHE DISHE', (SELECT id FROM authors WHERE name='UTPAL BANDOPADHYAY'), 'Library Shelf'),
('B/0268', 'NADI PATHE', (SELECT id FROM authors WHERE name='ATUL CHANDRA GUPTA'), 'Library Shelf'),
('B/0269', 'PAHAR THEKE PAHARE', (SELECT id FROM authors WHERE name='BISWA DEV BISWAS'), 'Library Shelf'),
('B/0270', 'SAMANNAYER SANDHANE', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0271', 'JE KATHA BAIJTE CHAI', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0272', 'NIMNABARGER ITIHAS', (SELECT id FROM authors WHERE name='GOUTAM BHADRA'), 'Library Shelf'),
('B/0273', 'VISWA ITIHAS FRASANGA', (SELECT id FROM authors WHERE name='JAWHARIAL NEHRU'), 'Library Shelf'),
('B/0274', 'MAYAK JUTHISTHIR', (SELECT id FROM authors WHERE name='DHIRESH CHANDRA BHATTACHARYA'), 'Library Shelf'),
('B/0275', 'GRAMIN BANK O AMAR JEEVAN', (SELECT id FROM authors WHERE name='MUHAMMAD UNUS'), 'Library Shelf'),
('B/0276', 'TARKAPRIYA BHARATIYA', (SELECT id FROM authors WHERE name='AMARTYA SEN'), 'Library Shelf'),
('B/0277', 'KALIKATA RAPPATH', (SELECT id FROM authors WHERE name='AJIT KUMAR BASU'), 'Library Shelf'),
('B/0278', 'ATMACHARIT', (SELECT id FROM authors WHERE name='JAWHARIAL NEHRU'), 'Library Shelf'),
('B/0279', 'KAMALA BAKTRIA O ANANYA BHASHAN', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0280', 'PALASHIR SHARAJANTRA O SEKALER SAMAI', (SELECT id FROM authors WHERE name='RAJAT KANTA ROY'), 'Library Shelf'),
('B/0281', 'EKAL SEKAL - PANCH PRAJAMYER ITIKATHA', (SELECT id FROM authors WHERE name='BHARATI ROY'), 'Library Shelf'),
('B/0282', 'UNNAYAN SWA-KSHAMATA', (SELECT id FROM authors WHERE name='AMARTYA SEN'), 'Library Shelf'),
('B/0283', 'MADHYA JUGER BHARATIYA SAHAR', (SELECT id FROM authors WHERE name='ANIRUDHDHA ROY'), 'Library Shelf'),
('B/0284', 'BHARATER ARTHIK BIKASH', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0285', 'KAJER BAJAR', (SELECT id FROM authors WHERE name='ANADABAZAR PATRIKA SANKALAN'), 'Library Shelf'),
('B/0286', 'ITALIR RENESANS-BANGALIR SANSKRITI', (SELECT id FROM authors WHERE name='AMALESH TRIPATHI'), 'Library Shelf'),
('B/0287', 'BHARATBARSHER PRAGITHAS', (SELECT id FROM authors WHERE name='DLIP KUMAR CHAKRABORTY'), 'Library Shelf'),
('B/0288', 'HINSA, PEEM O SWADESHCHINTA', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0289', 'ARTHANITIR JUKTI, TARKA O GALPA', (SELECT id FROM authors WHERE name='KOUSHIK BASU'), 'Library Shelf'),
('B/0290', 'ELSAMAY', (SELECT id FROM authors WHERE name='ANNADA SHANKAR ROY'), 'Library Shelf'),
('B/0291', 'BHARATER MUKTSANGRAM- CHARAMPARTHI PARVA', (SELECT id FROM authors WHERE name='AMALESH TRIPATHI'), 'Library Shelf'),
('B/0292', 'SETU BANDHAN', (SELECT id FROM authors WHERE name='ANNADA SHANKAR ROY'), 'Library Shelf'),
('B/0293', 'BHARATER ADHAPATAN', (SELECT id FROM authors WHERE name='T.N. SESHAN'), 'Library Shelf'),
('B/0294', 'AGNIPAKSHA', (SELECT id FROM authors WHERE name='A.P.I.ABDUL KALAM AZAD'), 'Library Shelf'),
('B/0295', 'SASWATA VIVEKANANDA', (SELECT id FROM authors WHERE name='NIMAI SADHAN BASU'), 'Library Shelf'),
('B/0296', 'MICRO OVEN E RANNA', (SELECT id FROM authors WHERE name='RUKMA DAKSHI'), 'Library Shelf'),
('B/0297', 'BHARATBARSHER KRISHI ARTHANITI', (SELECT id FROM authors WHERE name='ASHOK RUDRA'), 'Library Shelf'),
('B/0298', 'BHARAT ANDARER ABARODH', (SELECT id FROM authors WHERE name='M.I.AKGAR'), 'Library Shelf'),
('B/0299', 'MAHABHARATER CHARITABALI', (SELECT id FROM authors WHERE name='SUKHMAY BHATTACHARYA'), 'Library Shelf'),
('B/0300', 'BHARAT SANDHANE', (SELECT id FROM authors WHERE name='JAWHARIAL NEHRU'), 'Library Shelf'),
('B/0301', 'LEONARDO DA BHINCHI', (SELECT id FROM authors WHERE name='SVARI BREMLI'), 'Library Shelf'),
('B/0302', 'KOLKATA O DURGAPUJO', (SELECT id FROM authors WHERE name='ANJAN MITRA'), 'Library Shelf'),
('B/0303', 'EUROPE PUNADARSHAN', (SELECT id FROM authors WHERE name='TAPAN ROY CHOUDHARY'), 'Library Shelf'),
('B/0304', 'BHARATER RAHIBANIYA O VAIDESHIK LENDEN', (SELECT id FROM authors WHERE name='DHIRESH BHATTACHARYA'), 'Library Shelf'),
('B/0305', 'UPANISHAD - 1ST PART', (SELECT id FROM authors WHERE name='SWAMI LOKESHARANANDA'), 'Library Shelf'),
('B/0306', 'BANGALIR SAMYABAD CHARCHA', (SELECT id FROM authors WHERE name='SHIPRA SARKAR'), 'Library Shelf'),
('B/0307', 'AMANDASANGI', (SELECT id FROM authors WHERE name='ANADABAZAR PATRIKA SANKALAN'), 'Library Shelf'),
('B/0308', 'BHARATVARSHA-SWADHINATAR PARE', (SELECT id FROM authors WHERE name='BMWG CAMERON'), 'Library Shelf'),
('B/0309', 'MANUSANHITA', (SELECT id FROM authors WHERE name='SURESH CHANDRA BANDYOPADHYAY'), 'Library Shelf'),
('B/0310', 'ITIHASE BIGYAN', (SELECT id FROM authors WHERE name='J.D.BARNAL'), 'Library Shelf'),
('B/0311', 'MAHABHARATER DURLABH MUHURTA', (SELECT id FROM authors WHERE name='DHIRESH BHATTACHARYA'), 'Library Shelf'),
('B/0312', 'CHHARI KAKE BALE', (SELECT id FROM authors WHERE name='ASHOK MITRA'), 'Library Shelf'),
('B/0313', 'EUROPER BHASKARIVA', (SELECT id FROM authors WHERE name='ASHOK MITRA'), 'Library Shelf'),
('B/0314', 'AAMADER PADABIR ITIHAS', (SELECT id FROM authors WHERE name='LOKESHAWAR BASU'), 'Library Shelf'),
('B/0315', 'RASAJARAANJANE KOLKATA', (SELECT id FROM authors WHERE name='RUKMA DAKSHI'), 'Library Shelf'),
('B/0316', 'BANGLA NAME DESH', (SELECT id FROM authors WHERE name='ANANDABAZAR PATRIKA'), 'Library Shelf'),
('B/0317', 'SAT DASHAK', (SELECT id FROM authors WHERE name='ANANDABAZAR PATRIKA'), 'Library Shelf'),
('B/0318', 'KOLKATA-SEKAL O EKAL', (SELECT id FROM authors WHERE name='RATHIN MITRA'), 'Library Shelf'),
('B/0319', 'SHAKITR RUP- BHARATE O MADHYA ASIA I', (SELECT id FROM authors WHERE name='BRATINDRA NATII MUKHOPADHYAY'), 'Library Shelf'),
('B/0320', 'BHARATER CHITRAKALA-1ST PART', (SELECT id FROM authors WHERE name='ASHOK MITRA'), 'Library Shelf'),
('B/0322', 'BHARATER CHITRAKALA-2ND PART', (SELECT id FROM authors WHERE name='ASHOK MITRA'), 'Library Shelf'),
('B/0323', 'MADAM LADY-R DIARY', (SELECT id FROM authors WHERE name='NANDA DULAL DEY'), 'Library Shelf'),
('B/0324', 'TABA KATHAMRITAM', (SELECT id FROM authors WHERE name='SWAMI LOKESHAWARANANDA'), 'Library Shelf'),
('B/0325', 'JEEVAN JOUBAN', (SELECT id FROM authors WHERE name='ANNADA SHANKAR ROY'), 'Library Shelf'),
('B/0326', 'UPANISHAD-2ND PART', (SELECT id FROM authors WHERE name='SWAMI LOKESHAWARANANDA'), 'Library Shelf'),
('B/0327', 'PRACHIM BHARATE ARTHAMMITK ITIHASER SANIDHANE', (SELECT id FROM authors WHERE name='RAMABIR CHAKRABORTY'), 'Library Shelf'),
('B/0328', 'DESH BIBHAG-PASTAT O NEPATHYA KAHINI', (SELECT id FROM authors WHERE name='BHABANI PRASAD CHAKRABORTY'), 'Library Shelf'),
('B/0329', 'SHILP-E BHARAT O BAHIRBHARAT', (SELECT id FROM authors WHERE name='MINIDRA BIUSHAN GUPTA'), 'Library Shelf'),
('B/0330', 'SANDHIKSHAN', (SELECT id FROM authors WHERE name='ANNADA SHANKAR ROY'), 'Library Shelf'),
('B/0331', 'DARWIN THERE O N.A. EBONG CHARSHA KOTI BACHHAR', (SELECT id FROM authors WHERE name='NARAYAN SEN'), 'Library Shelf'),
('B/0332', 'DHARMA O PRAGATI', (SELECT id FROM authors WHERE name='JAYANTANUI BANDOPADHYAY'), 'Library Shelf'),
('B/0333', 'SHANTI SWARAI SANSKRITI', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0334', 'PASCHIM EUROPER CHITRAKALA', (SELECT id FROM authors WHERE name='ASHOK MITRA'), 'Library Shelf'),
('B/0335', 'JEEVANJATRA O ARTHANITI', (SELECT id FROM authors WHERE name='AMARTYA SEN'), 'Library Shelf'),
('B/0336', 'DESHNAYAK SUBHASHCHANDRA', (SELECT id FROM authors WHERE name='NIMAI SAOHAN BASU'), 'Library Shelf'),
('B/0337', 'RAMAYANER CHARITABALI', (SELECT id FROM authors WHERE name='SUKHAMAY BHATTACHARYA'), 'Library Shelf'),
('B/0338', 'JYOTIBABUR PASCHIMBANGA', (SELECT id FROM authors WHERE name='SHARMILA BASU'), 'Library Shelf'),
('B/0339', 'GABESHAMA-PATRA ANUSANDHAN O RACHAMA', (SELECT id FROM authors WHERE name='JAGMOHON MUKHOPADHYAY'), 'Library Shelf'),
('B/0340', 'PRABANDHA SANGRAHA - 2ND PART', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0341', 'SUBARMA SANGRAHA UPANYAS - 1ST PART', (SELECT id FROM authors WHERE name='ANANDA PUBLISHERS'), 'Library Shelf'),
('B/0342', 'SUBARMA SANGRAHA UPANYAS - 3RD PART', (SELECT id FROM authors WHERE name='ANANDA PUBLISHERS'), 'Library Shelf'),
('B/0343', 'SUBARMA SANGRAHA UPANYAS - 4TH PART', (SELECT id FROM authors WHERE name='ANANDA PUBLISHERS'), 'Library Shelf'),
('B/0344', 'SUBARMA SANGRAHA UPANYAS - 5TH PART', (SELECT id FROM authors WHERE name='ANANDA PUBLISHERS'), 'Library Shelf'),
('B/0345', 'SWET PATHARER THALA', (SELECT id FROM authors WHERE name='BANI BASU'), 'Library Shelf'),
('B/0346', 'MASHUL DHAR DIN', (SELECT id FROM authors WHERE name='AMITA AGNIHOTRI'), 'Library Shelf'),
('B/0347', 'BEHAR BAGI VANDUK', (SELECT id FROM authors WHERE name='TARUN KUMAR BHAOURI'), 'Library Shelf'),
('B/0348', 'RAJA, RANI, RAJSABHA-Y MADHARI', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0349', 'FALGUNER GANDHA', (SELECT id FROM authors WHERE name='SUKANTA GANGOPADHYAY'), 'Library Shelf'),
('B/0350', 'RANU O BHANU', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0351', 'JEEVANER JALSAGHARE', (SELECT id FROM authors WHERE name='MANNA DEY'), 'Library Shelf'),
('B/0352', 'ANDHARI', (SELECT id FROM authors WHERE name='SUKANTA CHATTAPADHYAY'), 'Library Shelf'),
('B/0353', 'HATIR BAI', (SELECT id FROM authors WHERE name='DHRITIKANTA LAHIRI CHOUDHURI'), 'Library Shelf'),
('B/0354', 'SHAMBA', (SELECT id FROM authors WHERE name='KALKUT'), 'Library Shelf'),
('B/0355', 'KHEROR KHATA', (SELECT id FROM authors WHERE name='LILA MAUIMDER'), 'Library Shelf'),
('B/0356', 'NIVEDITA RESEARCH LABORATORY', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0357', 'CRISCROS', (SELECT id FROM authors WHERE name='SMARAANJIT CHAKRABORTY'), 'Library Shelf'),
('B/0358', 'TISHIBHOR', (SELECT id FROM authors WHERE name='KETAKI KUSHARI DYSAN'), 'Library Shelf'),
('B/0359', 'BUDBUD', (SELECT id FROM authors WHERE name='SMARAANJIT CHAKRABORTY'), 'Library Shelf'),
('B/0360', 'JINNAH-BHARAT DESHBIAG SWADHINATA', (SELECT id FROM authors WHERE name='JASHAVANT SINGHA'), 'Library Shelf'),
('B/0361', 'MEGHEDER GHARBARI', (SELECT id FROM authors WHERE name='SUKANTA GANGOPADHYAY'), 'Library Shelf'),
('B/0362', 'GALPASAMAGRA', (SELECT id FROM authors WHERE name='RAMAPADA CHOUDHARY'), 'Library Shelf'),
('B/0363', 'BHATIR DESH', (SELECT id FROM authors WHERE name='AMITAVA GHOSH'), 'Library Shelf'),
('B/0364', 'KISHORE UPANVAS SAMAGRA (2)', (SELECT id FROM authors WHERE name='SIRSHENDU MUKHOPADHYAY'), 'Library Shelf'),
('B/0365', 'CHAPRAS', (SELECT id FROM authors WHERE name='BUDHDHADEY GUHA'), 'Library Shelf'),
('B/0366', 'JAL PARE PATA NARE', (SELECT id FROM authors WHERE name='GOUR KISHORE GHOSH'), 'Library Shelf'),
('B/0367', 'FELUDAR SAPTAKANDA', (SELECT id FROM authors WHERE name='SATYAJIT ROY'), 'Library Shelf'),
('B/0368', 'PANCHASHTI GALPO', (SELECT id FROM authors WHERE name='BIMAL KAR'), 'Library Shelf'),
('B/0369', 'DURBIN', (SELECT id FROM authors WHERE name='SIRSHENDU MUKHOPADHYAY'), 'Library Shelf'),
('B/0370', 'BHARAVI O SHIRRAMKRISHNA', (SELECT id FROM authors WHERE name='SANJIB CHATTOPADHYAY'), 'Library Shelf'),
('B/0371', 'KISHORE UPANVAS SAMAGRA (1)', (SELECT id FROM authors WHERE name='SIRSHENDU MUKHOPADHYAY'), 'Library Shelf'),
('B/0372', 'RASANARANJANE KOLKATA', (SELECT id FROM authors WHERE name='RUKMA DAKSHI'), 'Library Shelf'),
('B/0373', 'TENSION THEKE MUKTI', (SELECT id FROM authors WHERE name='DR. SHYAMAL CHAKRABORTY'), 'Library Shelf'),
('B/0374', 'PREM NEI', (SELECT id FROM authors WHERE name='GOUR KISHORE GHOSH'), 'Library Shelf'),
('B/0375', 'GALPO SAMAGRA (1)', (SELECT id FROM authors WHERE name='SUBODH GHOSH'), 'Library Shelf'),
('B/0376', 'RVNN', (SELECT id FROM authors WHERE name='TILOTTAMA MAJUMDER'), 'Library Shelf'),
('B/0377', 'GALPO SAMAGRA (3)', (SELECT id FROM authors WHERE name='SUBODH GHOSH'), 'Library Shelf'),
('B/0378', 'DUI MATALER GALPO O AMANYA', (SELECT id FROM authors WHERE name='TARAPADA ROY'), 'Library Shelf'),
('B/0379', 'BAOUL PHAKIR KATHA', (SELECT id FROM authors WHERE name='SUDHIR CHAKRABORTY'), 'Library Shelf'),
('B/0380', 'PRATIBESHI', (SELECT id FROM authors WHERE name='GOUR KISHORE GHOSH'), 'Library Shelf'),
('B/0381', 'DASTI UPANVAS', (SELECT id FROM authors WHERE name='MOTI NANDI'), 'Library Shelf'),
('B/0382', 'DESH - SUBARNAJAYANTI GALPO SANKALAN', (SELECT id FROM authors WHERE name='-'), 'Library Shelf'),
('B/0383', 'CHHAYABRITA', (SELECT id FROM authors WHERE name='SAMARESH MAJUMDER'), 'Library Shelf'),
('B/0384', 'CHAKRA', (SELECT id FROM authors WHERE name='SIRSHENDU MUKHOPADHYAY'), 'Library Shelf'),
('B/0385', 'BANGAL NAMA', (SELECT id FROM authors WHERE name='TAPAN ROY CHOUDHARY'), 'Library Shelf'),
('B/0386', 'SHRI SUBHASH CHANDRA BASU SAMAGRA RACHANABALI', (SELECT id FROM authors WHERE name='SUBHASH CHANDRA BOSE'), 'Library Shelf'),
('B/0387', 'SHRIMA', (SELECT id FROM authors WHERE name='AASHUTOSH MITRA'), 'Library Shelf'),
('B/0388', 'PURVA PASCHIM', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0389', 'STRIKER', (SELECT id FROM authors WHERE name='MOTI NANDI'), 'Library Shelf'),
('B/0390', 'KABULER PATHE PATHE', (SELECT id FROM authors WHERE name='PACHYAJAN'), 'Library Shelf'),
('B/0391', 'GANDHARBI', (SELECT id FROM authors WHERE name='BANI BASU'), 'Library Shelf'),
('B/0392', 'STOPPER', (SELECT id FROM authors WHERE name='MOTI NANDI'), 'Library Shelf'),
('B/0393', 'PATA JHARAR MARSHUME', (SELECT id FROM authors WHERE name='SMARANJIT CHAKRABORTY'), 'Library Shelf'),
('B/0394', 'PURBA PASCHIM (2ND VOL)', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0395', 'GALPO SAMAGRA (2)', (SELECT id FROM authors WHERE name='SUBODH GHOSH'), 'Library Shelf'),
('B/0396', 'GALPO MALA', (SELECT id FROM authors WHERE name='NARENDRA NATH MITRA'), 'Library Shelf'),
('B/0397', 'PAHARE FELUDA', (SELECT id FROM authors WHERE name='SATYAJIT ROY'), 'Library Shelf'),
('B/0398', 'HRIDAYE PREMIER SHIRSHA', (SELECT id FROM authors WHERE name='JOY GOSWAMI'), 'Library Shelf'),
('B/0399', 'AAPILA CHAAPILA', (SELECT id FROM authors WHERE name='ASHOK MITRA'), 'Library Shelf'),
('B/0400', 'AMRITA', (SELECT id FROM authors WHERE name='BANI BASU'), 'Library Shelf'),
('B/0401', 'NABABI AMALE MUHSHIDABAD', (SELECT id FROM authors WHERE name='SUSHIL CHOUDHARY'), 'Library Shelf'),
('B/0402', 'UPANYAS SAMAGRA - II', (SELECT id FROM authors WHERE name='RAMAPADA CHOUDHARY'), 'Library Shelf'),
('B/0403', 'UPANYAS SAMAGRA - III', (SELECT id FROM authors WHERE name='RAMAPADA CHOUDHARY'), 'Library Shelf'),
('B/0404', 'KAKABABU SAMAGRA', (SELECT id FROM authors WHERE name='SUNIL GANGOPADHYAY'), 'Library Shelf'),
('B/0405', 'DUI DASHAKER DESH (1983 - 2003) SAMKALAN', (SELECT id FROM authors WHERE name='-'), 'Library Shelf'),
('B/0406', 'SAHAI BANGLA BIBLE', (SELECT id FROM authors WHERE name='-'), 'Library Shelf'),
('B/0407', 'BENGALI TO ENGLISH DICTIONARY', (SELECT id FROM authors WHERE name='DEV SAHITYA KUTHIR'), 'Library Shelf'),
('B/0408', 'ENGLISH TO BENGALI & ENGLISH DICTIONARY', (SELECT id FROM authors WHERE name='DEV SAHITYA KUTHIR'), 'Library Shelf'),
('B/0409', 'PRABANDHA SANGRAHA', (SELECT id FROM authors WHERE name='AMLAN DUTTA'), 'Library Shelf'),
('B/0410', 'BANAPHULER CHOTO GALPO SAMAGRA - 1ST VOL', (SELECT id FROM authors WHERE name='BANA PHUL'), 'Library Shelf'),
('B/0411', 'GALPAMALA', (SELECT id FROM authors WHERE name='NARENDRA NATH MITRA'), 'Library Shelf'),
('B/0412', 'PANCHASHTI GALPO', (SELECT id FROM authors WHERE name='NAVA KUMAR BASU'), 'Library Shelf'),
('B/0413', 'SACAR JALE', (SELECT id FROM authors WHERE name='ATIN BANDOPADHYAY'), 'Library Shelf'),
('B/0414', 'BHUMI KANYA', (SELECT id FROM authors WHERE name='NILKANTHA GHOSHAL'), 'Library Shelf'),
('B/0415', 'PANCHASTI PRIVA GALPO', (SELECT id FROM authors WHERE name='SIRSHENDU MUKHOPADHYAY'), 'Library Shelf'),
('B/0416', 'BANAPHULER CHOTO GALPO SAMAGRA - 2ND VOL', (SELECT id FROM authors WHERE name='BANA PHUL'), 'Library Shelf'),
('B/0417', 'KORAAN SHARIF', (SELECT id FROM authors WHERE name='SOLEMANJA BOOK HOUSE'), 'Library Shelf'),
('B/0418', 'AAMI VIVEKANANDA BALCHHI', (SELECT id FROM authors WHERE name='SHANKAR'), 'Library Shelf'),
('B/0419', 'JE MAHATMA SARAWAN DWICHARITA KORE GECHHEN', (SELECT id FROM authors WHERE name='PRIYA RANJAN KUNDU'), 'Library Shelf'),
('B/0420', 'GABRIEL GARCIA MARQUEZ GALPOSAMAGRA', (SELECT id FROM authors WHERE name='-'), 'Library Shelf'),
('B/0421', 'DEEPTASHIKHA KSHUDIRAM', (SELECT id FROM authors WHERE name='SUSHANTA KUMAR SAHITYARATNA'), 'Library Shelf'),
('B/0422', 'ESHOPER GALPO', (SELECT id FROM authors WHERE name='TARAPADA RAHA'), 'Library Shelf'),
('B/0423', 'SERA GALPO SAMKALAN BETARJAGAT 1926-1986', (SELECT id FROM authors WHERE name='-'), 'Library Shelf'),
('B/0424', 'SHRI SHRI RAMKRISHNA KATHAMRITA', (SELECT id FROM authors WHERE name='SHRIM KATHITA'), 'Library Shelf'),
('B/0425', 'KOMAL GANDHAR', (SELECT id FROM authors WHERE name='USTAD BILAYET KHAN'), 'Library Shelf'),
('B/0426', 'CHHELEDER MAHABHARAT', (SELECT id FROM authors WHERE name='UPENDRA KISHORE ROY CHOUDHARY'), 'Library Shelf'),
('B/0427', 'NIRBACHITA BHUTER GALPO', (SELECT id FROM authors WHERE name='RANJIT CHATTOPADHYAY'), 'Library Shelf'),
('B/0428', 'AATMAGHATI RABINDRANATH', (SELECT id FROM authors WHERE name='NEERAD CHANDRA CHOUDHARY'), 'Library Shelf'),
('B/0429', 'PALASHIR AJANA KAHNI', (SELECT id FROM authors WHERE name='SUSHIL CHOUDHARY'), 'Library Shelf');